# === Frontend dockerfile ====

# Uses node version 22-alpine as our base image
FROM node:22-alpine

# Goes to the app directory (this container will have app folder)
WORKDIR /app

# Copy package.json and package-lock.json and puts it in the cache of the container
COPY package*.json ./

# Install app dependencies (like npm install)
RUN npm ci

# Copy code into the container
COPY . .

# Expose the port (React's default port) 
EXPOSE 3000

# Run the app
CMD ["npm", "run", "dev"]

